### PR TITLE
Fix bug with string index out of bounds

### PR DESCRIPTION
**Pull request by carl-textalk**

### CODE REVIEW

**Comment by carl-textalk** [comment]
There were a bug in the code causing a StringIndexOutOfBoundsException when trying to find a breakpoint.

**Comment by carl-textalk** [comment]
Hello @PaulRambags and @bertfrees.
We found a bug in this repository when trying to find a breakpoint and a StringIndexOutOfBoundsException was thrown. Could you please review this PR and give some feedback.

**Comment by carl-textalk** [comment]
Hello @PaulRambags and @bertfrees.
We found a bug in this repository when trying to find a breakpoint and a StringIndexOutOfBoundsException was thrown. Could you please review this PR and give some feedback.

**Comment by bertfrees** [comment]
Looks right to me.

**Comment by PaulRambags** [comment]
Thanks for not only fixing the bug, also for adding a unit test.
Approved.

**Review by kalaspuffar — APPROVED** [review]

**Comment by kalaspuffar** [comment]
Regression tests have been run. I will merge this PR.

**Pull request merged**
